# Generated by Django 6.0.1 on 2026-02-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreundebuchWebpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('public', models.BooleanField(default=False)),
                ('font_color', models.CharField(max_length=20)),
                ('font_style', models.CharField(max_length=20)),
                ('border_color', models.CharField(max_length=20)),
                ('border_width', models.CharField(max_length=20)),
                ('border_style', models.CharField(max_length=100)),
                ('border_radius', models.IntegerField()),
                ('additional_css', models.TextField()),
            ],
        ),
    ]
