# Generated by Django 6.0.1 on 2026-02-03 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FreundebuchWebpage', '0002_entrycustomization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntryCustomization',
        ),
    ]
