# Generated by Django 6.0.1 on 2026-02-10 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FreundebuchWebpage', '0003_delete_entrycustomization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
