# Generated by Django 6.0 on 2026-01-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0002_alter_entryv1_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entryv1',
            old_name='favorite_activity',
            new_name='biggest_idol',
        ),
        migrations.RenameField(
            model_name='entryv1',
            old_name='best_experience',
            new_name='craziest_experience',
        ),
        migrations.RenameField(
            model_name='entryv1',
            old_name='dream',
            new_name='loveliest_experience',
        ),
        migrations.AddField(
            model_name='entryv1',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
