# Generated by Django 6.0 on 2026-01-09 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0009_remove_createcode_id_alter_createcode_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryv1',
            name='custom_field_mode',
            field=models.CharField(blank=True, choices=[('txt', 'Text Field'), ('img', 'Image Field'), ('audio', 'Audio Field'), ('video', 'Video Field'), ('canvas', 'Canvas Field'), ('button', 'Button Field')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='CustomTextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Entries.entryv1')),
            ],
        ),
    ]
