# Generated by Django 6.0 on 2026-01-09 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0010_entryv1_custom_field_mode_customtextfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtextfield',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Entries.entryv1'),
            preserve_default=False,
        ),
    ]
