# Generated by Django 6.0 on 2026-01-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0011_alter_customtextfield_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryv1',
            name='custom_field_mode',
            field=models.CharField(blank=True, choices=[('txt', 'Text Field'), ('img', 'Image Field'), ('audio', 'Audio Field'), ('video', 'Video Field'), ('canvas', 'Canvas Field'), ('button', 'Button Field')], max_length=10, null=True),
        ),
    ]
