# Generated by Django 6.0.1 on 2026-01-15 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0012_alter_entryv1_custom_field_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAudioField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entries.entryv1')),
            ],
        ),
        migrations.CreateModel(
            name='CustomButtonField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onclick_url', models.URLField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entries.entryv1')),
            ],
        ),
        migrations.CreateModel(
            name='CustomCanvasField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entries.entryv1')),
            ],
        ),
        migrations.CreateModel(
            name='CustomImageField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entries.entryv1')),
            ],
        ),
        migrations.CreateModel(
            name='CustomVideoField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entries.entryv1')),
            ],
        ),
    ]
