# Generated by Django 6.0.1 on 2026-02-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0013_customaudiofield_custombuttonfield_customcanvasfield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryv1',
            name='biggest_idol',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='My biggest idol:'),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='My birthday is on:'),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='contact',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='How you can reach me:'),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='craziest_experience',
            field=models.CharField(blank=True, null=True, verbose_name='My craziest experience:'),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='dislikes',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="I really don't like:"),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='favorite_animal',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='favorite_book',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Book / Literature'),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='favorite_food',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Food'),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='favorite_movie',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Movie / Show'),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='favorite_music',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Music'),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='likes',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='I really like:'),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='I live in:'),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='loveliest_experience',
            field=models.CharField(blank=True, null=True, verbose_name='My loveliest experience:'),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='name',
            field=models.CharField(max_length=100, verbose_name='My name is:'),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='nicknames',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='People also call me:'),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='I am from:'),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='I am this tall:'),
        ),
        migrations.AlterField(
            model_name='entryv1',
            name='want_to_become',
            field=models.CharField(blank=True, null=True, verbose_name='In the future, I want to become...'),
        ),
    ]
