# Generated by Django 6.0.1 on 2026-02-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0015_entrycustomization_remove_entryv1_secret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrycustomization',
            name='border_width',
            field=models.IntegerField(),
        ),
    ]
