# Generated by Django 6.0.1 on 2026-02-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0016_alter_entrycustomization_border_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrycustomization',
            name='border_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entrycustomization',
            name='border_radius',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrycustomization',
            name='border_style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entrycustomization',
            name='border_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrycustomization',
            name='font_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entrycustomization',
            name='font_style',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entrycustomization',
            name='public',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
