# Generated by Django 6.0.1 on 2026-02-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0017_alter_entrycustomization_border_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrycustomization',
            name='background_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entrycustomization',
            name='additional_css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrycustomization',
            name='font_style',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
