# Generated by Django 6.0.1 on 2026-02-10 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCode',
            fields=[
                ('purpose', models.CharField(default='Unknown', max_length=100)),
                ('secret', models.CharField(default=apps.Entries.generate_secret.generate_secret, max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EntryCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('public', models.BooleanField(blank=True, default=False, null=True)),
                ('font_color', models.CharField(blank=True, max_length=20, null=True)),
                ('font_style', models.CharField(blank=True, max_length=30, null=True)),
                ('border_color', models.CharField(blank=True, max_length=20, null=True)),
                ('border_width', models.IntegerField(blank=True, null=True)),
                ('border_style', models.CharField(blank=True, max_length=100, null=True)),
                ('border_radius', models.IntegerField(blank=True, null=True)),
                ('background_color', models.CharField(blank=True, max_length=20, null=True)),
                ('additional_css', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntryV1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='My name is:')),
                ('nicknames', models.CharField(blank=True, max_length=500, null=True, verbose_name='People also call me:')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='My birthday is on:')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='I am this tall:')),
                ('origin', models.CharField(blank=True, max_length=100, null=True, verbose_name='I am from:')),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='I live in:')),
                ('contact', models.CharField(blank=True, max_length=500, null=True, verbose_name='How you can reach me:')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('likes', models.CharField(blank=True, max_length=500, null=True, verbose_name='I really like:')),
                ('dislikes', models.CharField(blank=True, max_length=500, null=True, verbose_name="I really don't like:")),
                ('loveliest_experience', models.CharField(blank=True, null=True, verbose_name='My loveliest experience:')),
                ('craziest_experience', models.CharField(blank=True, null=True, verbose_name='My craziest experience:')),
                ('favorite_food', models.CharField(blank=True, max_length=500, null=True, verbose_name='Food')),
                ('favorite_animal', models.CharField(blank=True, max_length=500, null=True, verbose_name='Animal')),
                ('favorite_book', models.CharField(blank=True, max_length=500, null=True, verbose_name='Book / Literature')),
                ('favorite_movie', models.CharField(blank=True, max_length=500, null=True, verbose_name='Movie / Show')),
                ('favorite_music', models.CharField(blank=True, max_length=500, null=True, verbose_name='Music')),
                ('biggest_idol', models.CharField(blank=True, max_length=500, null=True, verbose_name='My biggest idol:')),
                ('want_to_become', models.CharField(blank=True, null=True, verbose_name='In the future, I want to become...')),
                ('custom_field_mode', models.CharField(blank=True, choices=[('txt', 'Text Field'), ('img', 'Image Field'), ('audio', 'Audio Field'), ('video', 'Video Field'), ('canvas', 'Canvas Field'), ('button', 'Button Field')], max_length=10, null=True)),
                ('customization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Entries.entrycustomization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomVideoField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entries.entryv1')),
            ],
        ),
        migrations.CreateModel(
            name='CustomTextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entries.entryv1')),
            ],
        ),
        migrations.CreateModel(
            name='CustomImageField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entries.entryv1')),
            ],
        ),
        migrations.CreateModel(
            name='CustomCanvasField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entries.entryv1')),
            ],
        ),
        migrations.CreateModel(
            name='CustomButtonField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onclick_url', models.URLField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entries.entryv1')),
            ],
        ),
        migrations.CreateModel(
            name='CustomAudioField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entries.entryv1')),
            ],
        ),
    ]
