# Generated by Django 6.0.1 on 2026-05-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcanvasfield',
            name='canvas',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
