# Generated by Django 6.0.1 on 2026-02-24 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrycustomization',
            name='name',
        ),
        migrations.RemoveField(
            model_name='entrycustomization',
            name='public',
        ),
        migrations.RemoveField(
            model_name='entryv1',
            name='customization',
        ),
        migrations.AddField(
            model_name='entrycustomization',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Entries.entryv1'),
        ),
    ]
