# Generated by Django 6.0.1 on 2026-08-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0002_alter_customcanvasfield_canvas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryv1',
            name='birthday',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='My birthday is on:'),
        ),
    ]
