# Generated by Django 6.0.1 on 2026-02-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0002_remove_entrycustomization_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryv1',
            name='additional_css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entryv1',
            name='background_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entryv1',
            name='border_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entryv1',
            name='border_radius',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entryv1',
            name='border_style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entryv1',
            name='border_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entryv1',
            name='font_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entryv1',
            name='font_style',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='EntryCustomization',
        ),
    ]
