# Generated by Django 6.0.1 on 2026-02-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0003_entryv1_additional_css_entryv1_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryv1',
            name='font_family',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
