# Generated by Django 6.0.1 on 2026-02-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0004_entryv1_font_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryv1',
            name='enable_custom_style',
            field=models.BooleanField(default=False),
        ),
    ]
