# Generated by Django 6.0.1 on 2026-02-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0005_entryv1_enable_custom_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryv1',
            name='font_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
