# Generated by Django 6.0.1 on 2026-02-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0006_entryv1_font_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryv1',
            name='font_size',
        ),
        migrations.AddField(
            model_name='entryv1',
            name='answer_font_size',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='entryv1',
            name='question_font_size',
            field=models.IntegerField(default=20),
        ),
    ]
