# Generated by Django 6.0.1 on 2026-02-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0007_remove_entryv1_font_size_entryv1_answer_font_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryv1',
            name='field_background_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
