# Generated by Django 6.0.1 on 2026-02-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0008_entryv1_field_background_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entryv1',
            old_name='field_background_color',
            new_name='element_background_color',
        ),
    ]
