# Generated by Django 6.0.1 on 2026-02-25 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0009_rename_field_background_color_entryv1_element_background_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entryv1',
            old_name='font_family',
            new_name='font',
        ),
        migrations.RemoveField(
            model_name='entryv1',
            name='font_style',
        ),
    ]
